---
apiVersion: v1
kind: Secret
metadata:
  name: nickmartin1ee7-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-deploy/nickmartin1ee7-backend-gitops
